"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false 
format = """
 âœ\
$directory\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""
right_format = """$all"""
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os.symbols]
Windows = "ğŸªŸ"
Ubuntu = "ğŸ§"
SUSE = "ğŸ¦"
Raspbian = "ğŸ“"
Mint = "ğŸŒ¿"
Macos = "ğŸ"
Manjaro = "ğŸ¥­"
Linux = "ğŸ§"
Gentoo = "ğŸ—œï¸"
Fedora = "ğŸ©"
Alpine = "ğŸ”ï¸"
Amazon = "â˜ï¸"
Android = "ğŸ¤–"
Arch = "ğŸ—ï¸"
Artix = "ğŸ—ï¸"
CentOS = "ğŸ’ "
Debian = "ğŸŒ€"
Redhat = "ğŸ©"
RedHatEnterprise = "ğŸ©"

[username]
#show_always = true
#style_user = "bg:surface0 fg:text"
#style_root = "bg:surface0 fg:text"
#format = '[ $user ]($style)'

[aws]
disabled = true

[directory]
style = "sapphire"
format = " [$path]($style) "
#truncation_length = 4
#truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ğŸ“„"
"Downloads" = "ğŸ“¥"
"Music" = "ğŸµ"
"Pictures" = "ğŸ–¼ï¸"
"Developer" = "ğŸ’»"

[os]
disabled = true
#style = "bg:surface0 fg:text"

[custom.giturl]
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ğŸ™"
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ğŸ¦Š"
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ğŸª£"
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="ğŸ“š"
else
    GIT_REMOTE_SYMBOL="ğŸ“š"
fi
echo "$GIT_REMOTE_SYMBOL"
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output"

[git_branch]
symbol = "ğŸŒ¿ "
style = "lavender"
format = ' on [$symbol$branch]($style) '

[git_status]
format = '[($all_status$ahead_behind)]($style) '

[nodejs]
symbol = "ğŸŸ¢"
format = 'via [$symbol($version )]($style)'

[c]
symbol = "âš™ï¸"
format = 'via [$symbol($version(-$name) )]($style)'

[rust]
symbol = "ğŸ¦€"
format = 'via [$symbol($version )]($style)'

[golang]
symbol = "ğŸ¹"
format = 'via [$symbol($version )]($style)'
detect_files = ["go.mod"]

[php]
symbol = "ğŸ˜"
format = 'via [$symbol($version )]($style)'

[java]
symbol = "â˜•"
format = 'via [$symbol($version )]($style)'

[kotlin]
symbol = "ğŸ…º"
format = 'via [$symbol($version )]($style)'

[haskell]
symbol = "Î»"
format = 'via [$symbol($version )]($style)'

[python]
symbol = "ğŸ"
format = 'via [$symbol($version )]($style)'

[docker_context]
symbol = "ğŸ³"
format = 'via [$symbol$context]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[ğŸ•$time](fg:mantle bg:foam)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[â¯](bold fg:green)'
error_symbol = '[â¯](bold fg:red)'
vimcmd_symbol = '[â®](bold fg:green)'
vimcmd_replace_one_symbol = '[â®](bold fg:purple)'
vimcmd_replace_symbol = '[â®](bold fg:purple)'
vimcmd_visual_symbol = '[â®](bold fg:lavender)'

